### ISSUE TITLE
Some `Fprintf` statements aren't getting logged

### ISSUE THREAD

**Issue by sunny-b** [ahmetb/kubectl-foreach#13]
I noticed that on my Apple M1, some of the `Fprintf` statements aren't getting properly logged and I'm not sure why. FWIW, I tested it in a Linux container and it worked fine. And when I changed the code to log using `Fprintln`, it worked fine.

For some reason `Fprintf` and `Fprint` don't log on certain statements unless a `\n` is added.

I've only really noticed this with the `Continue? [Y/n]` statement, but might be happening with other ones that I haven't noticed. I'm guessing it might be due to my M1. This happens on both Terminal and iTerm.

Adding a screen recording to demonstrate what I mean: https://recordit.co/H3j8XTSUMo

**Comment by ahmetb** [comment]
Thanks for reporting. I don't have a Mac at the moment but I will try to repro. Fixes welcome in the meantime. 

This might be something that broke recently.

**Comment by sunny-b** [comment]
After some more testing, I think it's an issue with my terminal output. I'm going to close this ticket because I don't think it's impacting anyone else.
