### ISSUE TITLE
Question. Any option not to show "Will run command in context(s):"

### ISSUE THREAD

**Issue by mailsanchu** [ahmetb/kubectl-foreach#14]

**Comment by ahmetb** [comment]
It's explained in the -h/-help message.

**Comment by mailsanchu** [comment]
-q         Disable and accept confirmation prompts ($KUBECTL_FOREACH_DISABLE_PROMPTS) 
I am not talking about this one

**Comment by mailsanchu** [comment]
Usage:
    kubectl foreach [OPTIONS] [PATTERN]... -- [KUBECTL_ARGS...]

Patterns can be used to match context names from kubeconfig:
      (empty): matches all contexts
         NAME: matches context with exact name
    /PATTERN/: matches context with regular expression
        ^NAME: remove context with exact name from the matched results
   ^/PATTERN/: remove contexts matching the regular expression from the results
    
Options:
    -c=NUM     Limit parallel executions (default: 0, unlimited)
    -I=VAL     Replace VAL occurring in KUBECTL_ARGS with context name
    -q         Disable and accept confirmation prompts ($KUBECTL_FOREACH_DISABLE_PROMPTS) 
    -h/--help  Print help

Examples:
    # get nodes on contexts named a b c
    kubectl foreach a b c -- get nodes 

    # get nodes on all contexts named c0..9 except c1 (note the escaping)
    kubectl foreach '/^c[0-9]/' ^c1	 -- get nodes

    # get nodes on all contexts that has "prod" but not "foo"
    kubectl foreach /prod/ ^/foo/ -- get nodes

    # use 'kubectl tail' plugin to follow logs of pods in contexts named *test*
    kubectl foreach -I _ /test/ -- tail --context=_ -l app=foo

**Comment by mailsanchu** [comment]
![image](https://user-images.githubusercontent.com/32928538/212124250-4bc08349-cfa8-4af7-bdf0-9ee669f2cd32.png)

I am asking how to hide this information

**Comment by ahmetb** [comment]
Got it, thanks. I assumed `-q` was turning that off as well. I might've left that in there because it helped me a lot, especially to understand if I got the match patterns wrong.

What's the primary use case? Are you trying to parse the output, or is it just visual cosmetics?

**Comment by mailsanchu** [comment]
I am running this command in a loop and the above statement is repeating it. I would like to hide it if it is possible

**Comment by ahmetb** [comment]
Quickest fix would be fork & delete the code and recompile.

**Comment by mailsanchu** [comment]
Compile and copy the binary to some place? any instructions
